version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        command: sh -c "composer install"
        

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
          - target: 80
            published: ${WEB_PUBLISHED_PORT:-80}
            protocol: tcp
            mode: host
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        ports:
          - target: 3306
            published: ${DB_PUBLISHED_PORT:-3306}
            protocol: tcp
            mode: host
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - target: 8888
            published: ${PHPMYADMIN_PUBLISHED_PORT:-8888}
            protocol: tcp
            mode: host
        links:
            - db
        environment:
            PMA_HOST: ${DB_HOST:-db}
            PMA_PORT: ${DB_PUBLISHED_PORT:-3306}
            PMA_ARBITRARY: 1
            PMA_PASSWORD: ${DB_PASSWORD}
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # Adminer
    ####################################################################################################
    # adminer:
    #     image: adminer
    #     ports:
    #         - 9090:8080
    #     depends_on:
    #     - db
    #     environment:
    #         ADMINER_DEFAULT_SERVER: db
    #         ADMINER_DEFAULT_USERNAME: root
    #         ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
    #     volumes:
    #         - .docker/adminer/sessions:/sessions

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        image: axllent/mailpit:latest
        ports:
          - target: 8025
            published: ${MAILPIT_PUBLISHED_PORT:-8025}
            protocol: tcp
            mode: host
          - 1025:1025
        volumes:
        - .docker/mailpit/data:/data

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:latest
        command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379


    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     image: mariadb:latest
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}

    ####################################################################################################
    # PostgreSQL
    ####################################################################################################
    # db:
    #     image: postgres:latest
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - .docker/db/data:/var/lib/postgresql/data
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_PASSWORD=${DB_PASSWORD}
    #         - POSTGRES_DB=${DB_DATABASE}

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    #         - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    #     depends_on:
    #         - db

    ####################################################################################################
    # Reverb Service
    ####################################################################################################
    # reverb:
    #     build:
    #         context: .
    #         target: php
    #         args:
    #             - APP_ENV=${APP_ENV}
    #     environment:
    #         - APP_ENV=${APP_ENV}
    #         - CONTAINER_ROLE=reverb
    #     working_dir: /var/www
    #     volumes:
    #         - ./:/var/www
    #     ports:
    #         - 8888:8080
    #     depends_on:
    #         - db
    #         - redis
    
    ####################################################################################################
    # Queue Service
    ####################################################################################################
    # queue:
    #     build:
    #         context: .
    #         target: php
    #         args:
    #             - APP_ENV=${APP_ENV}
    #     environment:
    #         - APP_ENV=${APP_ENV}
    #         - CONTAINER_ROLE=queue
    #     working_dir: /var/www
    #     volumes:
    #         - ./:/var/www
    #     ports:
    #         - 8889:8080
    #     depends_on:
    #         - db
    #         - redis